### ISSUE TITLE
Missing Firebird.php file from 1.3.0 distribution

### ISSUE THREAD

**Issue by matheusd** [sebastianbergmann/dbunit#108]
Hello,

I just downloaded the lastest 1.3.0 dbunit package from pear, but it's missing the Firebird.php (PHPUnit/Extensions/Database/DB/MetaData/Firebird.php) file.

Does something need to be done to include it in the next DBUnit release?

Thanks.

**Comment by sebastianbergmann** [comment]
PEAR is no longer supported.
