### ISSUE TITLE
PHP Fatal error:  Cannot call constructor

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/dbunit#133]
Occurs in 
PHPUnit_Extensions_Database_Constraint_TableIsEqual, line 75
PHPUnit_Extensions_Database_Constraint_DataSetIsEqual, line 75

phpunit version: 3.7.32
dbunit version: dev-master ba82ea6
php version: 5.5.12

**Comment by patagu** [comment]
Thanks! Having the same problem, I downgraded dbunit from 1.3.2 to 1.3.1 and now it works.

phpunit version: 3.7.38
php version: 5.3.3

**Comment by sebastianbergmann** [comment]
PHPUnit 3.7 is no longer supported.
