### ISSUE TITLE
Booleans also must be treated in a special way

### ISSUE THREAD

**Issue by zerkms** [sebastianbergmann/dbunit#136]
In another pull request it was added a special case for comparing numeric values: https://github.com/sebastianbergmann/dbunit/commit/94e8237bb516889164b40a22da13aaa0c88a0c9f#diff-ff8d2de4c53f9d6000d6c4dbb9c90c34R167

But the thing is that database driver (PDO pgsql in my case) might also return booleans.

And since there is no way to specify a boolean value in a fixture file (they all are treated as strings) - the comparison `$thisValue !== $otherValue` is always evaluated to `false`.

**Comment by hairmare** [comment]
I ended up migrating to yml datasets since [src/DataSet/XmlDataSet.php#L67](https://github.com/sebastianbergmann/dbunit/blob/master/src/DataSet/XmlDataSet.php#L67) still contains it's `(string)` casting magic.

**Comment by PeteDevoy** [comment]
I changed to YAML after hairmare's suggestion but was still experiencing problems with PostgresSQL, eventually having to use PostgresSQL standard which is effectively a one char string in YAML, e.g.

    name: "Michael Moore"
    filmmaker: t
    athletic: f
