### ISSUE TITLE
Insert through DbUnit_ArrayDataSet with Oracle

### ISSUE THREAD

**Issue by ElodieBergonnier** [sebastianbergmann/dbunit#165]
Hello,

I am trying to initialize an Oracle XE database using a DbUnit_ArrayDataSet into the getDataSet() function.

The table is created using the query below:

``` sql
CREATE TABLE s_com_pop (
  com varchar(5) DEFAULT '',
  cataeu99 varchar(1) DEFAULT NULL,
  cataeu10 varchar(3) DEFAULT NULL,
  superf FLOAT,
  PRIMARY KEY (com)
) ;
```

The code below gives the initialization of the table s_com_pop :

``` php
    protected function getDataSet ()
    {
        return new Test_DbUnit_ArrayDataSet (
            array(
                's_com_pop' => array(
                    array('com' => '31555', 'cataeu99' => '1', 'cataeu10' => '111', 'superf' => 118.3),
                ),
            )
        );
```

During the execution, this error is displayed:

```
COMPOSITE[INSERT] operation failed on query: 
                INSERT INTO s_com_pop
                (com, cataeu99, cataeu10, superf)
                VALUES
                (?, ?, ?, ?)
             using args: Array
(
    [0] => 31555
    [1] => 1
    [2] => 111
    [3] => 118.3
)
 [SQLSTATE[HY000]: General error: 1722 OCIStmtExecute: ORA-01722: invalid number
 (ext\pdo_oci\oci_statement.c:148)]
```

So far, I have been able to track the issue to the 118.3 value. When I use an integer value (ex : 118), the query is correctly executed. So my guess is that the float value 118.3 is somehow converted to string during the process.

Some other clues:
- the code works fine with a Mysql or PostgreSQl databse,
- the query `INSERT INTO s_com_pop (com, cataeu99, cataeu10, superf)  VALUES ('31555',  '1', '111', 118.3);` throws no error when directly run into Oracle.

Best regards,

**Comment by elazar** [comment]
Offhand, I'm not seeing any reason why the float would be cast to a string. If you pass the values of `$query` and `$args` to `var_dump()` around [this line](https://github.com/sebastianbergmann/dbunit/blob/a0b24d7b98844377d6915381e956e3a6573b8844/PHPUnit/Extensions/Database/Operation/RowBased.php#L84), you should be able to double-check the data type. Please include that output here and we can proceed from there.

**Comment by ElodieBergonnier** [comment]
Thank you for your quick answer.

Here is the output:

```
query = 
                INSERT INTO s_com_pop
                (com, cataeu99, cataeu10, superf)
                VALUES
                (?, ?, ?, ?)
            
args = array(4) {
  [0]=>
  string(5) "31555"
  [1]=>
  string(1) "1"
  [2]=>
  string(3) "111"
  [3]=>
  float(118.3)
}
```

The 118.3 value is correctly stored as float. The problem should be elsewhere...
