### ISSUE TITLE
Expose DbUnit's functionality using a trait

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/dbunit#167]
https://github.com/sebastianbergmann/dbunit/commit/c5cada74d1e9a7aa0c26f90fcac950e45e89effd is initial work on a trait that provides the functionality of `PHPUnit_Extensions_Database_TestCase` (and can be used instead of it). This would allow to use DbUnit together with PHPUnit_Selenium, for instance.

**Comment by sebastianbergmann** [comment]
Implemented in `master`.

**Comment by gsouf** [comment]
@sebastianbergmann when can we expect it to be published in a stable version?

**Comment by sebastianbergmann** [comment]
This is already published in a stable version AFAIK.

**Comment by gsouf** [comment]
Ho, I'm very sorry, I only checked version 1 while it's in version 2. Thanks
