### ISSUE TITLE
Drop support for PHP < 5.6

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/dbunit#168]
PHPUnit 4.8, which was released today, is the last version of PHPUnit to support PHP 5.3, PHP 5.4, and PHP 5.5. I think that DbUnit should follow PHPUnit's lead and only support PHP 5.6 and PHP 7 in a DbUnit 2.0 release that should happen within the next two months.

Requiring a newer version of PHP would make new features such as #167 possible.

**Comment by elazar** [comment]
:+1:

**Comment by sebastianbergmann** [comment]
Implemented in `master`.
