### ISSUE TITLE
TestCaseTrait could not be loaded

### ISSUE THREAD

**Issue by etienneq** [sebastianbergmann/dbunit#174]
In some applications we do not use Composer's autoloader but our own of which until now I thought of being PSR-compatible.

In that cases loading of TestCaseTrait fails because Testcase specifies `use PHPUnit_Extensions_Database_TestCase_Trait;` but the filename is `Extensions/Database/TestCaseTrait.php` and not `Extensions/Database/TestCase/Trait.php` as expected. What's the reason for this? Am I missing something?

Kind regards,
Etienne

**Comment by sebastianbergmann** [comment]
Your autoloader is probably too eager and tries to load classes it is not responsible for.
