### ISSUE TITLE
ArrayDataSet: invalid initialization for mixed rows

### ISSUE THREAD

**Issue by balland** [sebastianbergmann/dbunit#179]
I have found out that the same list of columns should be used for all the rows even if this is not strictly needed.

The problem comes from the constructor of `ArrayDataSet`. The first row is used to decide which columns are available:
https://github.com/sebastianbergmann/dbunit/blob/master/src/Extensions/Database/DataSet/ArrayDataSet.php#L44

It would be more user-friendly to calculate the union of all the rows keys. And if this is not possible, at least yell during the construction instead of setting silently to null all the remaining columns.

**Comment by RusAlex** [comment]
Also met this limitation. 

At least this behavior should be documented. With "IMPORTANT" label. It was hard to realize why columns were not populated.

**Comment by nCrazed** [comment]
> The first row is used to decide which columns are available

It's worse than that, row with index `0` is used. So if you build an array via something like `array_filter` and forget to reset the keys, you will get no columns at all.

**Comment by nCrazed** [comment]
@sebastianbergmann I am still happy to implement a fix for this, just need a conformation that my proposed changes would be considered correct.
