### ISSUE TITLE
Suggestion: do not require, but suggest, symfony/yaml component

### ISSUE THREAD

**Issue by afoeder** [sebastianbergmann/dbunit#197]
In my `symfony/symfony 2.8` environment, it's not possible to install DbUnit (3.0) because it `requires symfony/yaml ^3.0`.

`symfony/symfony 2.8` on the other hand `replaces: symfony/yaml: v2.8.28` and therefore eventually dbunit 3.0 cannot be installed.

I don't plan to use the Yaml DataSet or the like; is it really necessary to _require_ symfony/yaml for dbunit?

**Comment by sebastianbergmann** [comment]
The right solution would be to split the Yaml-related code into a separate package.
