### ISSUE TITLE
trait not found

### ISSUE THREAD

**Issue by Amar-45** [sebastianbergmann/dbunit#202]
trait phpunit/dbunit/testcasetrait  not found while connecting dbunit with phpunit

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by Amar-45** [comment]
`<?php
use PHPUnit\Framework\TestCase;
use PHPUnit\DbUnit\TestCaseTrait;

abstract class SampleTest extends TestCase
{
    use TestCaseTrait;

    // only instantiate pdo once for test clean-up/fixture load
    static private $pdo = null;

    // only instantiate PHPUnit_Extensions_Database_DB_IDatabaseConnection once per test
    private $conn = null;

    public function getConnection()
    {
        if ($this->conn === null) {
            if (self::$pdo == null) {
                self::$pdo = new PDO($GLOBALS['DB_DSN'], $GLOBALS['DB_USER'], $GLOBALS['DB_PASSWD']);
            }
            $this->conn = $this->createDefaultDBConnection(self::$pdo, $GLOBALS['DB_DBNAME']);
        }
       
    }

    public function getDataSet()
    {
        return $this->createMySQLXMLDataSet('D:/xampp/htdocs/UnitTest/myFlatXmlFixture.xml');
    }

}
?>`

**Comment by Amar-45** [comment]
Iam using Php Version : 7.0 and phpunit version 6.4

**Comment by sebastianbergmann** [comment]
How did you install PHPUnit? How did you install DbUnit?

**Comment by Amar-45** [comment]
by using composer

**Comment by Amar-45** [comment]
iam stuck while connecting with db

**Comment by peter279k** [comment]
Hi @Amar-45, I don't have this problem.
And here is my [repo](https://github.com/peter279k/dbunit-sample) that you can refer.

I use the Same version for your specific version.
Check out the ```tests``` folder to see more details about this.

Thanks.
