### ISSUE TITLE
DBUNIT extension don't load anymore since phpunit 7.0.0

### ISSUE THREAD

**Issue by jrichard689** [sebastianbergmann/dbunit#206]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| DBunit                   | 3.0.3
| PHP version         | 7.1.2
| Installation Method | PHAR

Runnig PHPUNIT with DBUNIT extension don't work since 7.0.0 update

`php phpunit.phar -c phpunit.xml --verbose myTest.php`

Result of the command:

```
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.2 with Xdebug 2.5.5
Configuration: phpunit.xml
Extension:     tools_phpunit\dbunit.phar is not compatible with this version of PHPUnit

```
Start of the phpunit xml file:

```
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/7.0/phpunit.xsd"
         extensionsDirectory="tools_phpunit">

```

**Comment by sebastianbergmann** [comment]
DbUnit 4 has been released.
