### ISSUE TITLE
TestCaseTrait is not found

### ISSUE THREAD

**Issue by kschroeer** [sebastianbergmann/dbunit#211]
I have the following class declaration:

namespace MyAppTest\Integration\Rest;

use PHPUnit\DbUnit\TestCaseTrait;
use Zend\Http\Header\ContentType;
use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;

abstract class AbstractResourceTestCase extends AbstractHttpControllerTestCase
{
    use TestCaseTrait;
    ...
}

Running phpunit ends up in the errorr that TestCaseTrait was not found. I installed dbunit via composer.
As I saw, the TestCaseTrait has no namespace so PHPUnit\DbUnit is wrong?

**Comment by sebastianbergmann** [comment]
Which version of PHPUnit and DbUnit did you install?

**Comment by kschroeer** [comment]
Hi,

these are my versions:

phpunit => 5.7.27
dbunit => 2.0.3

and my testsuite should be executed on a machine with php 5.6.

**Comment by sebastianbergmann** [comment]
PHPUnit 5.7 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.
