### ISSUE TITLE
TRUNCATE fails on tables which have foreign key constraints

### ISSUE THREAD

**Issue by BRMatt** [sebastianbergmann/dbunit#37]
As of MySQL 5.5 `TRUNCATE` fails if the table being truncated [is referenced by foreign key constraints](http://dev.mysql.com/doc/innodb/1.1/en/innodb-other-changes-truncate.html) in other tables.

A temporary solution appears to be to disable foreign key checks before truncation and then re-enable them afterwards

http://zendframework.com/issues/browse/ZF-11235?focusedCommentId=45644&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-45644

**Comment by matiasbarone** [comment]
I'm using **Postgresql 9.4** and have the same problem.
I made it works using Cascade on the Truncate clause. To do that I override `getSetUpOperation` the following way. `PHPUnit_Extensions_Database_Operation_Factory::CLEAN_INSERT()` support receiving boolean to force the cascade

```php
	/**
	 * Returns the database operation executed in test setup.
	 *
	 * @return PHPUnit_Extensions_Database_Operation_DatabaseOperation
	 */
	protected function getSetUpOperation() {
		return PHPUnit_Extensions_Database_Operation_Factory::CLEAN_INSERT ( true );
	}
```
