### ISSUE TITLE
Oracle error when DBUnit read the metadatas of a table prefixed by a schema

### ISSUE THREAD

**Issue by dlanoire** [sebastianbergmann/dbunit#41]
Hi,

When I use a  xml file as initialization dataset with tables names prefixed by the schema, there is an Oracle error when accessing to the metadata tables :
ORA-00904: "OWNER": invalid identifier: SELECT DISTINCT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='TEST_PDO' AND OWNER = 'DENIS' ORDER BY COLUMN_NAME 

The bug is coming from the class PHPUnit_Extensions_Database_DB_MetaData_Oci which is using the table USER_TAB_COLUMNS the get the columns of a table BUT there is no column OWNER in this table because it shows only the table columns the current user owns. Instead of this table, you should use the table ALL_TAB_COLUMNS which shows the tables the current user is granted. 
Same problem to get the primary key of a table, you must replace the user_constraints and user_cons_columns tables by all_constraints and all_cons_columns 

Furthermore, in the same class, I suggest that you use the SQL command DELETE FROM instead of TRUNCATE TABLE to initialize the tables (default behavior), since Oracle requires high privileges to truncate a table. I know that TRUNCATE is faster than DELETE and reset autoincrement keys but a simple user is rarely granted TRUNCATE privileges.

My PHP version is 5.3.5 and PHPUnit version is 3.5.14.
My db server is Oracle Express 10g and I used Windows XP SP3 for the client and the server.
### Test script:

``` php
class MyTest extends PHPUnit_Extensions_Database_TestCase { 
static private $pdo = null;
private $conn = null; 
protected function getConnection() {
   if ($this->conn === null) {
     if (self::$pdo == null) {
       self::$pdo = new PDO('oci://localhost/XE', 'denis', 'mypassw');
     }
     $this->conn = $this->createDefaultDBConnection(self::$pdo, 'DENIS');
   } 
  self::$pdo->setAttribute(PDO::ATTR_AUTOCOMMIT, FALSE);
   return $this->conn; 
} 
protected function getDataSet() {
   return $this->createFlatXMLDataSet(dirname(__FILE__).'/files/seed.xml');
 } 
public function testDummy () {}
 } 
```
### My xml file dataset seed.xml  (replace table prefix by your schema) :

``` xml
<?xml version="1.0" encoding="UTF-8"?>
 <dataset>
       <DENIS.TEST_PDO ID="1" VALUE="eviter les caracteres accentues" QTY="421.35" />
      <DENIS.TEST_PDO ID="2" VALUE="libelle sans accents" QTY="-17.85" />
 </dataset>
```
### The SQL to create the test table :

``` sql
CREATE TABLE "TEST_PDO"
 ( "ID" NUMBER, 
  "VALUE" VARCHAR2(250),
 "QTY" NUMBER, 
CONSTRAINT "TEST_PDO_PK" PRIMARY KEY ("ID") ENABLE )
```

Best Regards,

**Comment by wrampd** [comment]
Has anyone found a workaround for this -- really don't want to edit the libs  -- keeps upgrades difficult. Same problem -- oracle.
