### ISSUE TITLE
Yaml DataSet - Symfony Yaml Componet changed in actual release

### ISSUE THREAD

**Issue by HawkOfLight** [sebastianbergmann/dbunit#60]
Hi,

I've installed the Symfony Yaml-Component via Pear as described in the documentation (http://symfony.com/components) and tried to use it.  PHPUnit process exited with the message:

PHP Fatal error:  main(): Failed opening required 'SymfonyComponents/YAML/sfYaml.php' ...

After checking the include paths I found out that neither the path nor the filename used to include the yaml component existed. A view into the Symfony Sources (https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Yaml) shows that the required file no longer exists / the paths were changed.

Regards,

Robert

**Comment by sebastianbergmann** [comment]
PEAR is no longer supported.
