### ISSUE TITLE
assertTablesEqual - failure description, tables diff

### ISSUE THREAD

**Issue by Halama** [sebastianbergmann/dbunit#62]
When assertion that two tables are equal fails, whole content of both tables is printed out side by side.
Find what caused the failure in content of both tables can be really time consuming and uncofortable.
Some kind of diff output of both tables would be really helpful.

**Comment by januzis** [comment]
Ditto. At least a message like "Failed asserting that _actualfieldvalue_  equals _expectedfieldvalue_" would be nice.
