### ISSUE TITLE
Warn/throw if a non-existing dataset was given

### ISSUE THREAD

**Issue by xrstf** [sebastianbergmann/dbunit#85]
I was just debugging our test cases and got the following error:

```
1) sly_DB_PDO_PersistenceTest::testGetPDO
Invalid argument supplied for foreach()

Q:\...\tests\sly\BaseTest.php:50
Q:\...\tests\sly\BaseTest.php:30
```

In line 50, I only had the line

```
$core = new PHPUnit_Extensions_Database_DataSet_YamlDataSet(dirname(__FILE__).'/../datasets/'.$name.'.yml');
```

It took me a while to figure out that the file path was wrong and DbUnit could simply not find the dataset file.

It would be good if the datasets check the existence of the files (or at least whether parsing the YAML returned an array) and throws a meaningful exception if the dataset is invalid.

**Comment by jdreddaway** [comment]
Seconded! Thankfully Google brought me here!
